repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.1
  hooks:
    - id: pycln
      args: [ --all ]
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    args: [ -l 88]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.237'
  hooks:
    - id: ruff
