repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: file-contents-sorter
      files: requirements.in
- repo: https://github.com/hadialqattan/pycln
  rev: v2.2.2
  hooks:
    - id: pycln
      args: [ --all ]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    args: [ -l 88]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.287'
  hooks:
    - id: ruff
