[tool.ruff]
select = ["E", "F", "I"]
ignore = []

fix = true
unfixable = []

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 88

target-version = "py39"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "E402"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.isort]
profile = "black"
