services:

  torchserve:
    build:
      context: ../..
      dockerfile: inference_torchserve/docker/dockerfiles/DockerfileTorchServe
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
